#ifndef _BOARDS_DECT_DONGLE_H
#define _BOARDS_DECT_DONGLE_H

#include "boards/pico.h"

#undef PICO_DEFAULT_LED_PIN
#define PICO_DEFAULT_LED_PIN 2

#undef PICO_BOOT_STAGE2_CHOOSE_W25Q080
#define PICO_BOOT_STAGE2_CHOOSE_W25Q080 0

#define PICO_BOOT_STAGE2_CHOOSE_GENERIC_03H 1

#undef PICO_FLASH_SPI_CLKDIV
#define PICO_FLASH_SPI_CLKDIV 4

#undef PICO_FLASH_SIZE_BYTES
#define PICO_FLASH_SIZE_BYTES (2 * 1024 * 1024)

#endif
